export const staticBookData = [
  {
    id: "1",
    name: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Fiction",
    description: "A classic novel that explores the decadence of the Jazz Age.",
    price: 12,
    quantity: 50,
    rating: 3,
    language: "English",
    publisher: "Charles Scribner's Sons",
    publishedAt: 2000,
  },
  {
    id: "2",
    name: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Classics",
    description:
      "A poignant novel addressing racial injustice in the American South.",
    price: 14,
    rating: 3,
    quantity: 40,
    language: "English",
    publisher: "J.B. Lippincott & Co.",
    publishedAt: 2000,
  },
  {
    id: "3",
    name: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    description: "A classic novel depicting a totalitarian future society.",
    price: 10,
    rating: 4,
    quantity: 30,
    language: "English",
    publisher: "Secker & Warburg",
    publishedAt: 1949,
  },
  {
    id: "4",
    name: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    description:
      "A timeless novel exploring love and social class in early 19th-century England.",
    price: 11,
    rating: 5,
    quantity: 35,
    language: "English",
    publisher: "T. Egerton, Whitehall",
    publishedAt: 1813,
  },
];
